services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: spring_app
      POSTGRES_USER: nashtech
      POSTGRES_PASSWORD: nashtech
    ports:
      - '5432:5432'
    volumes:
      - ./src/main/resources/persistence:/docker-entrypoint-initdb.d