-- permissions.sql
GRANT ALL PRIVILEGES ON DATABASE investor_db TO nashtech;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO nashtech;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO nashtech;
GRANT USAGE, CREATE ON SCHEMA public TO nashtech;
GRANT CREATE ON SCHEMA public TO nashtech;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO nashtech;
ALTER SCHEMA public OWNER TO nashtech;


