---- Create builder table
--CREATE TABLE builder (
--    id SERIAL PRIMARY KEY,
--    name VARCHAR(100),
--    company VARCHAR(100),
--    contact_info TEXT
--);
--
---- Create property table
--CREATE TABLE property (
--    id SERIAL PRIMARY KEY,
--    location VARCHAR(255),
--    owner VARCHAR(100)
--);
--
---- Create employee table with foreign key reference to builder table
--CREATE TABLE employee (
--    id SERIAL PRIMARY KEY,
--    name VARCHAR(100),
--    property_id INT,
--    role VARCHAR(50),
--    builder_id INT,
--    FOREIGN KEY (property_id) REFERENCES builder(id),
--    FOREIGN KEY (builder_id) REFERENCES builder(id)
--);
--
---- Create user_property table with foreign key reference to property table
--CREATE TABLE user_property (
--    id SERIAL PRIMARY KEY,
--    user_id INT,
--    property_id INT,
--    owner_id INT,
--    property_details TEXT,
--    FOREIGN KEY (property_id) REFERENCES property(id)
--);
--
---- Create user_group table
--CREATE TABLE user_groups (
--    id SERIAL PRIMARY KEY,
--    user_id INT,
--    role VARCHAR(50),
--    name VARCHAR(100)
--);
--
---- Create property_documents table with foreign key reference to property table
--CREATE TABLE property_documents (
--    id SERIAL PRIMARY KEY,
--    property_id INT,
--    document_link TEXT,
--    FOREIGN KEY (property_id) REFERENCES property(id)
--);
