---- Insert data into builder
--INSERT INTO builder (name, company, contact_info) VALUES
--('Builder1', 'Company1', 'builder1@example.com'),
--('Builder2', 'Company2', 'builder2@example.com'),
--('Builder3', 'Company3', 'builder3@example.com'),
--('Builder4', 'Company4', 'builder4@example.com'),
--('Builder5', 'Company5', 'builder5@example.com');
--
---- Insert data into property
--INSERT INTO property (location, owner) VALUES
--('Location1', 'Owner1'),
--('Location2', 'Owner2'),
--('Location3', 'Owner3'),
--('Location4', 'Owner4'),
--('Location5', 'Owner5');
--
---- Insert data into employee (property_id must reference existing builder records)
--INSERT INTO employee (name, property_id, role, builder_id) VALUES
--('Employee1', 1, 'Admin', 1),
--('Employee2', 2, 'Manager', 2),
--('Employee3', 3, 'Developer', 3),
--('Employee4', 4, 'Tester', 4),
--('Employee5', 5, 'Support', 5);
--
---- Insert data into user_property (property_id must reference existing property records)
--INSERT INTO user_property (user_id, property_id, owner_id, property_details) VALUES
--(1, 1, 101, 'Property located in City A, 3-bedroom house'),
--(2, 2, 102, 'Property located in City B, 2-bedroom apartment'),
--(3, 3, 103, 'Property located in City C, 4-bedroom villa'),
--(4, 4, 104, 'Property located in City D, 1-bedroom studio'),
--(5, 5, 105, 'Property located in City E, 5-bedroom mansion');
--
---- Insert data into user_group
--INSERT INTO user_groups (user_id, role, name) VALUES
--(1, 'Admin', 'Admin Group'),
--(2, 'Viewer', 'Viewers Group'),
--(3, 'Editor', 'Editors Group'),
--(4, 'Contributor', 'Contributors Group'),
--(5, 'Guest', 'Guests Group');
--
---- Insert data into property_documents (property_id must reference existing property records)
--INSERT INTO property_documents (property_id, document_link) VALUES
--(1, 'http://example.com/doc1'),
--(2, 'http://example.com/doc2'),
--(3, 'http://example.com/doc3'),
--(4, 'http://example.com/doc4'),
--(5, 'http://example.com/doc5');
